### PR TITLE
realsense_camera: Add patch to correct link the node...

### PR DESCRIPTION
**Pull request by mbelluzzo**
*** PLZ dont forget to update the manifest after this is merged ***

... when the system library is used.

Signed-off-by: Murilo Belluzzo <murilo.belluzzo@intel.com>

### CODE REVIEW

**Comment by mbelluzzo** [comment]
Tested and solve the undefined symbol problem. Patch will be submitted upstream as well.

**Comment by icoderaven** [comment]
This works! Can confirm depth images coming in @60Hz!

**Comment by mbelluzzo** [comment]
Awesome! Thanks for the confirmation!

**Comment by icoderaven** [comment]
No worries! Also, the python error seems to be coming via
dynamic_reconfigure, but i could change the parameters fine.

**Pull request merged**
